//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Codice sorgente generato automaticamente da xsd, versione=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://api.irishrail.ie/realtime/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://api.irishrail.ie/realtime/", IsNullable=false)]
public partial class ArrayOfObjStation {
    
    private ArrayOfObjStationObjStation[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("objStation")]
    public ArrayOfObjStationObjStation[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://api.irishrail.ie/realtime/")]
public partial class ArrayOfObjStationObjStation {
    
    private string stationDescField;
    
    private string stationAliasField;
    
    private string stationLatitudeField;
    
    private string stationLongitudeField;
    
    private string stationCodeField;
    
    private string stationIdField;
    
    /// <remarks/>
    public string StationDesc {
        get {
            return this.stationDescField;
        }
        set {
            this.stationDescField = value;
        }
    }
    
    /// <remarks/>
    public string StationAlias {
        get {
            return this.stationAliasField;
        }
        set {
            this.stationAliasField = value;
        }
    }
    
    /// <remarks/>
    public string StationLatitude {
        get {
            return this.stationLatitudeField;
        }
        set {
            this.stationLatitudeField = value;
        }
    }
    
    /// <remarks/>
    public string StationLongitude {
        get {
            return this.stationLongitudeField;
        }
        set {
            this.stationLongitudeField = value;
        }
    }
    
    /// <remarks/>
    public string StationCode {
        get {
            return this.stationCodeField;
        }
        set {
            this.stationCodeField = value;
        }
    }
    
    /// <remarks/>
    public string StationId {
        get {
            return this.stationIdField;
        }
        set {
            this.stationIdField = value;
        }
    }
}
