//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Codice sorgente generato automaticamente da xsd, versione=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://api.irishrail.ie/realtime/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://api.irishrail.ie/realtime/", IsNullable=false)]
public partial class ArrayOfObjStationFilter {
    
    private ArrayOfObjStationFilterObjStationFilter[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("objStationFilter")]
    public ArrayOfObjStationFilterObjStationFilter[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://api.irishrail.ie/realtime/")]
public partial class ArrayOfObjStationFilterObjStationFilter {
    
    private string stationDesc_spField;
    
    private string stationDescField;
    
    private string stationCodeField;
    
    /// <remarks/>
    public string StationDesc_sp {
        get {
            return this.stationDesc_spField;
        }
        set {
            this.stationDesc_spField = value;
        }
    }
    
    /// <remarks/>
    public string StationDesc {
        get {
            return this.stationDescField;
        }
        set {
            this.stationDescField = value;
        }
    }
    
    /// <remarks/>
    public string StationCode {
        get {
            return this.stationCodeField;
        }
        set {
            this.stationCodeField = value;
        }
    }
}
