//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Codice sorgente generato automaticamente da xsd, versione=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://api.irishrail.ie/realtime/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://api.irishrail.ie/realtime/", IsNullable=false)]
public partial class ArrayOfObjTrainPositions {
    
    private ArrayOfObjTrainPositionsObjTrainPositions[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("objTrainPositions")]
    public ArrayOfObjTrainPositionsObjTrainPositions[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://api.irishrail.ie/realtime/")]
public partial class ArrayOfObjTrainPositionsObjTrainPositions {
    
    private string trainStatusField;
    
    private string trainLatitudeField;
    
    private string trainLongitudeField;
    
    private string trainCodeField;
    
    private string trainDateField;
    
    private string publicMessageField;
    
    private string directionField;
    
    /// <remarks/>
    public string TrainStatus {
        get {
            return this.trainStatusField;
        }
        set {
            this.trainStatusField = value;
        }
    }
    
    /// <remarks/>
    public string TrainLatitude {
        get {
            return this.trainLatitudeField;
        }
        set {
            this.trainLatitudeField = value;
        }
    }
    
    /// <remarks/>
    public string TrainLongitude {
        get {
            return this.trainLongitudeField;
        }
        set {
            this.trainLongitudeField = value;
        }
    }
    
    /// <remarks/>
    public string TrainCode {
        get {
            return this.trainCodeField;
        }
        set {
            this.trainCodeField = value;
        }
    }
    
    /// <remarks/>
    public string TrainDate {
        get {
            return this.trainDateField;
        }
        set {
            this.trainDateField = value;
        }
    }
    
    /// <remarks/>
    public string PublicMessage {
        get {
            return this.publicMessageField;
        }
        set {
            this.publicMessageField = value;
        }
    }
    
    /// <remarks/>
    public string Direction {
        get {
            return this.directionField;
        }
        set {
            this.directionField = value;
        }
    }
}
