//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Codice sorgente generato automaticamente da xsd, versione=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://api.irishrail.ie/realtime/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://api.irishrail.ie/realtime/", IsNullable=false)]
public partial class ArrayOfObjStationData {
    
    private ArrayOfObjStationDataObjStationData[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("objStationData")]
    public ArrayOfObjStationDataObjStationData[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://api.irishrail.ie/realtime/")]
public partial class ArrayOfObjStationDataObjStationData {
    
    private string servertimeField;
    
    private string traincodeField;
    
    private string stationfullnameField;
    
    private string stationcodeField;
    
    private string querytimeField;
    
    private string traindateField;
    
    private string originField;
    
    private string destinationField;
    
    private string origintimeField;
    
    private string destinationtimeField;
    
    private string statusField;
    
    private string lastlocationField;
    
    private string dueinField;
    
    private string lateField;
    
    private string exparrivalField;
    
    private string expdepartField;
    
    private string scharrivalField;
    
    private string schdepartField;
    
    private string directionField;
    
    private string traintypeField;
    
    private string locationtypeField;
    
    /// <remarks/>
    public string Servertime {
        get {
            return this.servertimeField;
        }
        set {
            this.servertimeField = value;
        }
    }
    
    /// <remarks/>
    public string Traincode {
        get {
            return this.traincodeField;
        }
        set {
            this.traincodeField = value;
        }
    }
    
    /// <remarks/>
    public string Stationfullname {
        get {
            return this.stationfullnameField;
        }
        set {
            this.stationfullnameField = value;
        }
    }
    
    /// <remarks/>
    public string Stationcode {
        get {
            return this.stationcodeField;
        }
        set {
            this.stationcodeField = value;
        }
    }
    
    /// <remarks/>
    public string Querytime {
        get {
            return this.querytimeField;
        }
        set {
            this.querytimeField = value;
        }
    }
    
    /// <remarks/>
    public string Traindate {
        get {
            return this.traindateField;
        }
        set {
            this.traindateField = value;
        }
    }
    
    /// <remarks/>
    public string Origin {
        get {
            return this.originField;
        }
        set {
            this.originField = value;
        }
    }
    
    /// <remarks/>
    public string Destination {
        get {
            return this.destinationField;
        }
        set {
            this.destinationField = value;
        }
    }
    
    /// <remarks/>
    public string Origintime {
        get {
            return this.origintimeField;
        }
        set {
            this.origintimeField = value;
        }
    }
    
    /// <remarks/>
    public string Destinationtime {
        get {
            return this.destinationtimeField;
        }
        set {
            this.destinationtimeField = value;
        }
    }
    
    /// <remarks/>
    public string Status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    public string Lastlocation {
        get {
            return this.lastlocationField;
        }
        set {
            this.lastlocationField = value;
        }
    }
    
    /// <remarks/>
    public string Duein {
        get {
            return this.dueinField;
        }
        set {
            this.dueinField = value;
        }
    }
    
    /// <remarks/>
    public string Late {
        get {
            return this.lateField;
        }
        set {
            this.lateField = value;
        }
    }
    
    /// <remarks/>
    public string Exparrival {
        get {
            return this.exparrivalField;
        }
        set {
            this.exparrivalField = value;
        }
    }
    
    /// <remarks/>
    public string Expdepart {
        get {
            return this.expdepartField;
        }
        set {
            this.expdepartField = value;
        }
    }
    
    /// <remarks/>
    public string Scharrival {
        get {
            return this.scharrivalField;
        }
        set {
            this.scharrivalField = value;
        }
    }
    
    /// <remarks/>
    public string Schdepart {
        get {
            return this.schdepartField;
        }
        set {
            this.schdepartField = value;
        }
    }
    
    /// <remarks/>
    public string Direction {
        get {
            return this.directionField;
        }
        set {
            this.directionField = value;
        }
    }
    
    /// <remarks/>
    public string Traintype {
        get {
            return this.traintypeField;
        }
        set {
            this.traintypeField = value;
        }
    }
    
    /// <remarks/>
    public string Locationtype {
        get {
            return this.locationtypeField;
        }
        set {
            this.locationtypeField = value;
        }
    }
}
