//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Codice sorgente generato automaticamente da xsd, versione=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://api.irishrail.ie/realtime/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://api.irishrail.ie/realtime/", IsNullable=false)]
public partial class ArrayOfObjTrainMovements {
    
    private ArrayOfObjTrainMovementsObjTrainMovements[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("objTrainMovements")]
    public ArrayOfObjTrainMovementsObjTrainMovements[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://api.irishrail.ie/realtime/")]
public partial class ArrayOfObjTrainMovementsObjTrainMovements {
    
    private string trainCodeField;
    
    private string trainDateField;
    
    private string locationCodeField;
    
    private string locationFullNameField;
    
    private string locationOrderField;
    
    private string locationTypeField;
    
    private string trainOriginField;
    
    private string trainDestinationField;
    
    private string scheduledArrivalField;
    
    private string scheduledDepartureField;
    
    private string expectedArrivalField;
    
    private string expectedDepartureField;
    
    private string arrivalField;
    
    private string departureField;
    
    private string autoArrivalField;
    
    private string autoDepartField;
    
    private string stopTypeField;
    
    /// <remarks/>
    public string TrainCode {
        get {
            return this.trainCodeField;
        }
        set {
            this.trainCodeField = value;
        }
    }
    
    /// <remarks/>
    public string TrainDate {
        get {
            return this.trainDateField;
        }
        set {
            this.trainDateField = value;
        }
    }
    
    /// <remarks/>
    public string LocationCode {
        get {
            return this.locationCodeField;
        }
        set {
            this.locationCodeField = value;
        }
    }
    
    /// <remarks/>
    public string LocationFullName {
        get {
            return this.locationFullNameField;
        }
        set {
            this.locationFullNameField = value;
        }
    }
    
    /// <remarks/>
    public string LocationOrder {
        get {
            return this.locationOrderField;
        }
        set {
            this.locationOrderField = value;
        }
    }
    
    /// <remarks/>
    public string LocationType {
        get {
            return this.locationTypeField;
        }
        set {
            this.locationTypeField = value;
        }
    }
    
    /// <remarks/>
    public string TrainOrigin {
        get {
            return this.trainOriginField;
        }
        set {
            this.trainOriginField = value;
        }
    }
    
    /// <remarks/>
    public string TrainDestination {
        get {
            return this.trainDestinationField;
        }
        set {
            this.trainDestinationField = value;
        }
    }
    
    /// <remarks/>
    public string ScheduledArrival {
        get {
            return this.scheduledArrivalField;
        }
        set {
            this.scheduledArrivalField = value;
        }
    }
    
    /// <remarks/>
    public string ScheduledDeparture {
        get {
            return this.scheduledDepartureField;
        }
        set {
            this.scheduledDepartureField = value;
        }
    }
    
    /// <remarks/>
    public string ExpectedArrival {
        get {
            return this.expectedArrivalField;
        }
        set {
            this.expectedArrivalField = value;
        }
    }
    
    /// <remarks/>
    public string ExpectedDeparture {
        get {
            return this.expectedDepartureField;
        }
        set {
            this.expectedDepartureField = value;
        }
    }
    
    /// <remarks/>
    public string Arrival {
        get {
            return this.arrivalField;
        }
        set {
            this.arrivalField = value;
        }
    }
    
    /// <remarks/>
    public string Departure {
        get {
            return this.departureField;
        }
        set {
            this.departureField = value;
        }
    }
    
    /// <remarks/>
    public string AutoArrival {
        get {
            return this.autoArrivalField;
        }
        set {
            this.autoArrivalField = value;
        }
    }
    
    /// <remarks/>
    public string AutoDepart {
        get {
            return this.autoDepartField;
        }
        set {
            this.autoDepartField = value;
        }
    }
    
    /// <remarks/>
    public string StopType {
        get {
            return this.stopTypeField;
        }
        set {
            this.stopTypeField = value;
        }
    }
}
